### ISSUE TITLE
Which general direction does stonks go?

### ISSUE THREAD

**Issue by chriskilinc** [peterheinum/quppy#1]
A cording to the source code I can't seem to determine the general direction of which way the stonks go. 
Please dev team, could you elaborate?  🤷‍♂️

**Comment by peterheinum** [comment]
This is a completely unessecary comment because of the well known fact that stonks ONLY go up. Closing this issue due to not being a real issue.

**Comment by chriskilinc** [comment]
I will have to beg to differ because as a matter of fact, your stonks has yet to go up past the collected value of purchase, but actually gone down. Reopening the issue. 

- [x] Stonks goes down
- [x] Stonks goes up

**Comment by peterheinum** [comment]
Reopening this issue until stonks actually have gone up.  😞🚀

I am just kidding stonks are up.
